<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
 <head>
  <meta http-equiv="content-type" content="text/html; CHARSET=UTF-8">
  <title>The OutOfBoundsException class</title>
<link media="all" rel="stylesheet" type="text/css" href="styles/03e73060321a0a848018724a6c83de7f-theme-base.css" />
<link media="all" rel="stylesheet" type="text/css" href="styles/03e73060321a0a848018724a6c83de7f-theme-medium.css" />

  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <link media="all" rel="stylesheet" type="text/css" href="style.css"/>
 </head>
 <body class="docs" class="docs"><div class="navbar navbar-fixed-top">
  <div class="navbar-inner clearfix">
    <ul class="nav" style="width: 100%">
      <li style="float: left;"><a href="class.logicexception.html">? LogicException</a></li>
      <li style="float: right;"><a href="class.outofrangeexception.html">OutOfRangeException ?</a></li>
    </ul>
  </div>
</div>
<div id="breadcrumbs" class="clearfix">
  <ul class="breadcrumbs-container">
    <li><a href="index.html">PHP Manual</a></li>
    <li><a href="spl.exceptions.html">异常</a></li>
    <li>The OutOfBoundsException class</li>
  </ul>
</div>
<div id="layout">
  <div id="layout-content"><div id="class.outofboundsexception" class="reference">
 <h1 class="title">The OutOfBoundsException class</h1>
 
 
 <div class="partintro"><p class="verinfo">(PHP 5 &gt;= 5.1.0, PHP 7, PHP 8)</p>
 

  <div class="section" id="outofboundsexception.intro">
   <h2 class="title">简介</h2>
   <p class="para">
    Exception thrown if a value is not a valid key. This represents errors
    that cannot be detected at compile time.
   </p>
  </div>

 
  <div class="section" id="outofboundsexception.synopsis">
   <h2 class="title">类摘要</h2>
 

   <div class="classsynopsis">
    <span class="ooclass">
     <strong class="classname"></strong>
    </span>

    <div class="classsynopsisinfo">
     <span class="ooclass">
      <span class="modifier">class</span> <strong class="classname">OutOfBoundsException</strong>
     </span>

     <span class="ooclass">
      <span class="modifier">extends</span>
       <a href="class.runtimeexception.html" class="classname">RuntimeException</a>
     </span>
     {</div>

    <div class="classsynopsisinfo classsynopsisinfo_comment">/* 继承的属性 */</div>
    <div class="fieldsynopsis">
     <span class="modifier">protected</span>
     <span class="type">string</span>
      <var class="varname"><a href="class.exception.html#exception.props.message">$<var class="varname">message</var></a></var><span class="initializer"> = &quot;&quot;</span>;</div>
<div class="fieldsynopsis"><span class="modifier">private</span>
     <span class="type">string</span>
      <var class="varname"><a href="class.exception.html#exception.props.string">$<var class="varname">string</var></a></var><span class="initializer"> = &quot;&quot;</span>;</div>
<div class="fieldsynopsis"><span class="modifier">protected</span>
     <span class="type">int</span>
      <var class="varname"><a href="class.exception.html#exception.props.code">$<var class="varname">code</var></a></var>;</div>
<div class="fieldsynopsis"><span class="modifier">protected</span>
     <span class="type">string</span>
      <var class="varname"><a href="class.exception.html#exception.props.file">$<var class="varname">file</var></a></var><span class="initializer"> = &quot;&quot;</span>;</div>
<div class="fieldsynopsis"><span class="modifier">protected</span>
     <span class="type">int</span>
      <var class="varname"><a href="class.exception.html#exception.props.line">$<var class="varname">line</var></a></var>;</div>
<div class="fieldsynopsis"><span class="modifier">private</span>
     <span class="type">array</span>
      <var class="varname"><a href="class.exception.html#exception.props.trace">$<var class="varname">trace</var></a></var><span class="initializer"> = []</span>;</div>
<div class="fieldsynopsis"><span class="modifier">private</span>
     <span class="type">?</span><span class="type"><span class="type"><a href="class.throwable.html" class="type Throwable">Throwable</a></span><span class="type"></span></span>
      <var class="varname"><a href="class.exception.html#exception.props.previous">$<var class="varname">previous</var></a></var><span class="initializer"> = null</span>;</div>


    <div class="classsynopsisinfo classsynopsisinfo_comment">/* 继承的方法 */</div>
    <div class="constructorsynopsis dc-description">
   <span class="modifier">public</span> <span class="methodname"><a href="exception.construct.html" class="methodname">Exception::__construct</a></span>(<span class="methodparam"><span class="type">string</span> <code class="parameter">$message</code><span class="initializer"> = &quot;&quot;</span></span>, <span class="methodparam"><span class="type">int</span> <code class="parameter">$code</code><span class="initializer"> = 0</span></span>, <span class="methodparam"><span class="type">?</span><span class="type"><span class="type"><a href="class.throwable.html" class="type Throwable">Throwable</a></span><span class="type"></span></span> <code class="parameter">$previous</code><span class="initializer"> = <strong><code>null</code></strong></span></span>)</div>

    <div class="methodsynopsis dc-description"><span class="modifier">final</span> <span class="modifier">public</span> <span class="methodname"><a href="exception.getmessage.html" class="methodname">Exception::getMessage</a></span>(): <span class="type">string</span></div>
<div class="methodsynopsis dc-description"><span class="modifier">final</span> <span class="modifier">public</span> <span class="methodname"><a href="exception.getprevious.html" class="methodname">Exception::getPrevious</a></span>(): <span class="type"><span class="type">?</span><span class="type"><a href="class.throwable.html" class="type Throwable">Throwable</a></span></span></div>
<div class="methodsynopsis dc-description"><span class="modifier">final</span> <span class="modifier">public</span> <span class="methodname"><a href="exception.getcode.html" class="methodname">Exception::getCode</a></span>(): <span class="type">int</span></div>
<div class="methodsynopsis dc-description"><span class="modifier">final</span> <span class="modifier">public</span> <span class="methodname"><a href="exception.getfile.html" class="methodname">Exception::getFile</a></span>(): <span class="type">string</span></div>
<div class="methodsynopsis dc-description"><span class="modifier">final</span> <span class="modifier">public</span> <span class="methodname"><a href="exception.getline.html" class="methodname">Exception::getLine</a></span>(): <span class="type">int</span></div>
<div class="methodsynopsis dc-description"><span class="modifier">final</span> <span class="modifier">public</span> <span class="methodname"><a href="exception.gettrace.html" class="methodname">Exception::getTrace</a></span>(): <span class="type">array</span></div>
<div class="methodsynopsis dc-description"><span class="modifier">final</span> <span class="modifier">public</span> <span class="methodname"><a href="exception.gettraceasstring.html" class="methodname">Exception::getTraceAsString</a></span>(): <span class="type">string</span></div>
<div class="methodsynopsis dc-description"><span class="modifier">public</span> <span class="methodname"><a href="exception.tostring.html" class="methodname">Exception::__toString</a></span>(): <span class="type">string</span></div>
<div class="methodsynopsis dc-description"><span class="modifier">private</span> <span class="methodname"><a href="exception.clone.html" class="methodname">Exception::__clone</a></span>(): <span class="type"><span class="type void">void</span></span></div>

   }</div>

 
  </div>
 
 </div>
 
 
 
</div>
<div id="usernotes">
 <div class="head">
  <h3 class="title">User Contributed Notes</h3>
 </div>
<div id="allnotes">  <a name="127166""></a>
  <div class="note">
   <strong class="user">Anonymous</strong>
   <a href="#127166" class="date">09-Jun-2022 12:52</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
I would probably repeat @jacub's answer, but I see the distinction as following:<br />
<br />
`OutOfBoundsException` you throw, when _you_ _set_ bounds and do not wish them to be crossed by an external entity, but they may be.<br />
Example: you ask for a number in range [1, 6] and user input 0 or 7 or what else. You throw an exception indicating user error they could amend.<br />
<br />
`OutOfRangeException` you throw, when you expect value within allowed boundary, but actual operation fails.<br />
Example: You are trying to access external API call using information provided by the API itself, and it suddenly tell you that the reference key is not pointing to a valid object. You throw an exception indicating internal failure that the user is unable to correct.<br />
<br />
In both cases, the key word is "you throw". Both exceptions are generated at runtime, but the latter describes a situation that should not happen, ever, if a system is configured correctly.</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="121092""></a>
  <div class="note">
   <strong class="user">Jakub Adamczyk</strong>
   <a href="#121092" class="date">16-May-2017 11:35</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
I see this in this way:<br />
By definiton, OutOfRangeException should be use to when potential problem is logical. This (OutOfBoundsException) is for runtime, so it's perfect for catching errors which occur because of bad result from database and simillar.<br />
<br />
Example of using OutOfBoundSException (see also note in "OutOfRangeException class" article):<br />
<br />
<span class="default">&lt;?php<br />
</span><span class="keyword">class </span><span class="default">HandleApplication </span><span class="keyword">{<br />
&nbsp;&nbsp;&nbsp; public function </span><span class="default">__construct</span><span class="keyword">(</span><span class="default">$_POST</span><span class="keyword">) {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; if(!isset(</span><span class="default">$_POST</span><span class="keyword">[</span><span class="string">'secretCode'</span><span class="keyword">])<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; throw new </span><span class="default">OutOfBoundsException</span><span class="keyword">(</span><span class="string">'Application hasn'</span><span class="default">t sent secret code </span><span class="keyword">for </span><span class="default">authenticate</span><span class="string">');<br />
}</span>
</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="120533""></a>
  <div class="note">
   <strong class="user">evguenia dot chagnon at gmail dot com</strong>
   <a href="#120533" class="date">26-Jan-2017 12:58</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
class MyDynamicTastyPie implements ArrayAccess{<br />
&nbsp;&nbsp;&nbsp; private $_pointeur = 0;<br />
&nbsp;&nbsp;&nbsp; private $_array = ['strawberry slice','white chocolate','nuts'];<br />
&nbsp;&nbsp;&nbsp; <br />
&nbsp;&nbsp;&nbsp; public function offsetExists($key){<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; return isset($this-&gt;_array[$key]);<br />
&nbsp;&nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; <br />
&nbsp;&nbsp;&nbsp; public function offsetGet($key){<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; if ($key &gt; count($this-&gt;_array)){<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; throw new OutOfBoundsException('Your tasty pie doesn\'t contain so slices');<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; }<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; return $this-&gt;_array[$key];<br />
&nbsp;&nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; <br />
&nbsp;&nbsp;&nbsp; public function offsetSet($key, $value){<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; $this-&gt;_array[$key] =$value;<br />
&nbsp;&nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; <br />
&nbsp;&nbsp;&nbsp; public function offsetUnset($key){<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; unset($this-&gt;_array[$key]);<br />
&nbsp;&nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; <br />
&nbsp;&nbsp;&nbsp; public function addSlice($slice){<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; $this-&gt;_array[] = $slice;<br />
&nbsp;&nbsp;&nbsp; }<br />
}<br />
<br />
try {<br />
&nbsp;&nbsp;&nbsp; $myDynamicTastyPie = new MyDynamicTastyPie();<br />
&nbsp;&nbsp;&nbsp; $myDynamicTastyPie-&gt;addSlice('Black chocolate cream decoration');<br />
&nbsp;&nbsp;&nbsp; echo $myDynamicTastyPie[7];<br />
}<br />
catch(OutOfBoundsException $e){<br />
&nbsp;&nbsp;&nbsp; echo 'Here is your OutOfBoundsException!';<br />
}</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="119547""></a>
  <div class="note">
   <strong class="user">sricharan dot krishnan at gmail dot com</strong>
   <a href="#119547" class="date">04-Jul-2016 10:48</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
An example where an OutOfBoundsException can occur:<br />
Lets say post a certain division process, we wish to access a value in an Array [provided ofcourse if the result value of the division is within the size of the Array]..<br />
<br />
try{<br />
&nbsp;&nbsp;&nbsp; if ($iNum2 == 0){<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; throw new Exception("Division by Zero");<br />
&nbsp;&nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; $iResult = $iNum1 / $iNum2;<br />
&nbsp;&nbsp;&nbsp; echo ("Division result is: ".($iResult)."&lt;br/&gt;");<br />
}<br />
catch (Exception $e){<br />
&nbsp;&nbsp;&nbsp; echo ("Division by Zero is not possible.".($e)."&lt;br/&gt;");<br />
}<br />
<br />
$rg_Array = array(1,2,3,4);<br />
<br />
try{<br />
&nbsp;&nbsp;&nbsp; if ($iResult &gt; sizeof($rg_Array)- 1){<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; throw new Exception("Exceeding key values");<br />
&nbsp;&nbsp;&nbsp; }<br />
echo ("Capturing value from \$rg_Array post Division process:".($rg_Array[$iResult])."&lt;br/&gt;");<br />
}<br />
catch (Exception $e){<br />
&nbsp;&nbsp;&nbsp; echo ("Value of Division result is out of bounds for the array.".($e)."&lt;br/&gt;");<br />
}<br />
?&gt;</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="117790""></a>
  <div class="note">
   <strong class="user">Jacob V. Rasmussen</strong>
   <a href="#117790" class="date">11-Aug-2015 08:49</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
OutOfRangeException is for Integers out of range.
<br />
OutOfBoundsException is for key values, not found in the target array.
<br />

<br />
Editor's note: This is incorrect; OutOfRangeException has *nothing* to do with Integer ranges. I decided to keep this highly voted comment even though it is wrong for education's sake.</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="116103""></a>
  <div class="note">
   <strong class="user">Anonymous</strong>
   <a href="#116103" class="date">10-Nov-2014 03:29</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
i wish i know what's the difference between <br />
OutOfRangeException and OutOfBoundsException lol</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
</div>
</div>
</div></div></body></html>
