<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
 <head>
  <meta http-equiv="content-type" content="text/html; CHARSET=UTF-8">
  <title>设置用户自定义的异常处理函数</title>
<link media="all" rel="stylesheet" type="text/css" href="styles/03e73060321a0a848018724a6c83de7f-theme-base.css" />
<link media="all" rel="stylesheet" type="text/css" href="styles/03e73060321a0a848018724a6c83de7f-theme-medium.css" />

  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <link media="all" rel="stylesheet" type="text/css" href="style.css"/>
 </head>
 <body class="docs" class="docs"><div class="navbar navbar-fixed-top">
  <div class="navbar-inner clearfix">
    <ul class="nav" style="width: 100%">
      <li style="float: left;"><a href="function.set-error-handler.html">? set_error_handler</a></li>
      <li style="float: right;"><a href="function.trigger-error.html">trigger_error ?</a></li>
    </ul>
  </div>
</div>
<div id="breadcrumbs" class="clearfix">
  <ul class="breadcrumbs-container">
    <li><a href="index.html">PHP Manual</a></li>
    <li><a href="ref.errorfunc.html">错误处理 函数</a></li>
    <li>设置用户自定义的异常处理函数</li>
  </ul>
</div>
<div id="layout">
  <div id="layout-content"><div id="function.set-exception-handler" class="refentry">
 <div class="refnamediv">
  <h1 class="refname">set_exception_handler</h1>
  <p class="verinfo">(PHP 5, PHP 7, PHP 8)</p><p class="refpurpose"><span class="refname">set_exception_handler</span> &mdash; <span class="dc-title">
   设置用户自定义的异常处理函数
  </span></p>

 </div>

 <div class="refsect1 description" id="refsect1-function.set-exception-handler-description">
  <h3 class="title">说明</h3>
  <div class="methodsynopsis dc-description">
   <span class="methodname"><strong>set_exception_handler</strong></span>(<span class="methodparam"><span class="type">?</span><span class="type"><span class="type"><a href="language.types.callable.html" class="type callable">callable</a></span><span class="type"></span></span> <code class="parameter">$callback</code></span>): <span class="type"><span class="type">?</span><span class="type"><a href="language.types.callable.html" class="type callable">callable</a></span></span></div>

  <p class="para rdfs-comment">
   设置默认的异常处理程序，用于没有用 try/catch 块来捕获的异常。
   在 <code class="parameter">callback</code> 调用后异常会中止。
  </p>
 </div>


 <div class="refsect1 parameters" id="refsect1-function.set-exception-handler-parameters">
  <h3 class="title">参数</h3>
  <p class="para">
   <dl>
    
     <dt>
<code class="parameter">callback</code></dt>

     <dd>

      <p class="para">
       当一个未捕获的异常发生时所调用的函数。该处理函数需要接受一个参数，该参数是抛出的
       <span class="classname"><a href="class.throwable.html" class="classname">Throwable</a></span> 对象。<span class="classname"><a href="class.error.html" class="classname">Error</a></span>
       和 <span class="classname"><a href="class.exception.html" class="classname">Exception</a></span> 都实现了 <span class="classname"><a href="class.throwable.html" class="classname">Throwable</a></span>
       接口。这是处理程序签名：       
      </p>
      <p class="para">
       <div class="methodsynopsis dc-description">
        <span class="methodname"><span class="replaceable">handler</span></span>(<span class="methodparam"><span class="type"><a href="class.throwable.html" class="type Throwable">Throwable</a></span> <code class="parameter">$ex</code></span>): <span class="type"><span class="type void">void</span></span></div>

      </p>
      <p class="para">
        也可以传递 <strong><code>null</code></strong> 值用于重置异常处理函数为默认值。
      </p>
     </dd>

    
   </dl>

  </p>
 </div>


 <div class="refsect1 returnvalues" id="refsect1-function.set-exception-handler-returnvalues">
  <h3 class="title">返回值</h3>
  <p class="para">
   返回之前定义的异常处理程序，或者在错误时返回
   <strong><code>null</code></strong>。如果之前没有定义错误处理程序，也会返回 <strong><code>null</code></strong>。
  </p>
 </div>

 
 <div class="refsect1 examples" id="refsect1-function.set-exception-handler-examples">
  <h3 class="title">示例</h3>
  <p class="para">
   <div class="example" id="example-1046">
    <p><strong>Example #1 <span class="function"><strong>set_exception_handler()</strong></span> 范例</strong></p>
    <div class="example-contents">
<div class="phpcode"><code><span style="color: #000000">
<span style="color: #0000BB">&lt;?php<br /></span><span style="color: #007700">function </span><span style="color: #0000BB">exception_handler</span><span style="color: #007700">(</span><span style="color: #0000BB">Throwable $exception</span><span style="color: #007700">) {<br />  echo </span><span style="color: #DD0000">"Uncaught exception: " </span><span style="color: #007700">, </span><span style="color: #0000BB">$exception</span><span style="color: #007700">-&gt;</span><span style="color: #0000BB">getMessage</span><span style="color: #007700">(), </span><span style="color: #DD0000">"\n"</span><span style="color: #007700">;<br />}<br /><br /></span><span style="color: #0000BB">set_exception_handler</span><span style="color: #007700">(</span><span style="color: #DD0000">'exception_handler'</span><span style="color: #007700">);<br /><br />throw new </span><span style="color: #0000BB">Exception</span><span style="color: #007700">(</span><span style="color: #DD0000">'Uncaught Exception'</span><span style="color: #007700">);<br />echo </span><span style="color: #DD0000">"Not Executed\n"</span><span style="color: #007700">;<br /></span><span style="color: #0000BB">?&gt;</span>
</span>
</code></div>
    </div>

   </div>
  </p>
 </div>


 <div class="refsect1 seealso" id="refsect1-function.set-exception-handler-seealso">
  <h3 class="title">参见</h3>
  <p class="para">
   <ul class="simplelist">
    <li class="member"><span class="function"><a href="function.restore-exception-handler.html" class="function" rel="rdfs-seeAlso">restore_exception_handler()</a> - 恢复之前定义过的异常处理函数。</span></li>
    <li class="member"><span class="function"><a href="function.restore-error-handler.html" class="function" rel="rdfs-seeAlso">restore_error_handler()</a> - 还原之前的错误处理函数</span></li>
    <li class="member"><span class="function"><a href="function.error-reporting.html" class="function" rel="rdfs-seeAlso">error_reporting()</a> - 设置应该报告何种 PHP 错误</span></li>
    <li class="member"><a href="language.exceptions.html" class="link">异常</a></li>
   </ul>
  </p>
 </div>


</div><div id="usernotes">
 <div class="head">
  <h3 class="title">User Contributed Notes</h3>
 </div>
<div id="allnotes">  <a name="125102""></a>
  <div class="note">
   <strong class="user">ohcc at 163 dot com</strong>
   <a href="#125102" class="date">09-Jun-2020 04:05</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
As of PHP 7.4, an exception thrown within the user-defined shutdown function can be caught by the user-defined exception handler.<br />
<br />
<span class="default">&lt;?php<br />
&nbsp;&nbsp;&nbsp; set_error_handler</span><span class="keyword">(<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; function(</span><span class="default">$level</span><span class="keyword">, </span><span class="default">$error</span><span class="keyword">, </span><span class="default">$file</span><span class="keyword">, </span><span class="default">$line</span><span class="keyword">){<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; if(</span><span class="default">0 </span><span class="keyword">=== </span><span class="default">error_reporting</span><span class="keyword">()){<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; return </span><span class="default">false</span><span class="keyword">;<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; }<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; throw new </span><span class="default">ErrorException</span><span class="keyword">(</span><span class="default">$error</span><span class="keyword">, -</span><span class="default">1</span><span class="keyword">, </span><span class="default">$level</span><span class="keyword">, </span><span class="default">$file</span><span class="keyword">, </span><span class="default">$line</span><span class="keyword">);<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; },<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">E_ALL<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">);<br />
<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">register_shutdown_function</span><span class="keyword">(function(){<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">$error </span><span class="keyword">= </span><span class="default">error_get_last</span><span class="keyword">();<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; if(</span><span class="default">$error</span><span class="keyword">){<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; throw new </span><span class="default">ErrorException</span><span class="keyword">(</span><span class="default">$error</span><span class="keyword">[</span><span class="string">'message'</span><span class="keyword">], -</span><span class="default">1</span><span class="keyword">, </span><span class="default">$error</span><span class="keyword">[</span><span class="string">'type'</span><span class="keyword">], </span><span class="default">$error</span><span class="keyword">[</span><span class="string">'file'</span><span class="keyword">], </span><span class="default">$error</span><span class="keyword">[</span><span class="string">'line'</span><span class="keyword">]);<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; });<br />
<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">set_exception_handler</span><span class="keyword">(function(</span><span class="default">$exception</span><span class="keyword">){<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; </span><span class="comment">// ... more code ...<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">});&nbsp; &nbsp; <br />
&nbsp;&nbsp;&nbsp; <br />
&nbsp;&nbsp;&nbsp; require </span><span class="string">'NotExists.php'</span><span class="keyword">;</span>
</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="121629""></a>
  <div class="note">
   <strong class="user">klaussantana at gmail dot com</strong>
   <a href="#121629" class="date">12-Sep-2017 03:44</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
Hi everyone. I don't know if it is an old behavior of previous versions, but currently you can set exception and error handlers as private or protected methos, if, only if, you call `set_exception_handler()` or `set_error_handler()` within a context that can access the method.<br />
<br />
Example:<br />
&nbsp;&nbsp;&nbsp; <span class="default">&lt;?PHP<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; $Handler </span><span class="keyword">= new class ()<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; {<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; public function </span><span class="default">__construct </span><span class="keyword">()<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; {<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">set_error_handler</span><span class="keyword">([</span><span class="default">$this</span><span class="keyword">, </span><span class="string">'HandleError'</span><span class="keyword">);<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">set_exception_handler</span><span class="keyword">([</span><span class="default">$this</span><span class="keyword">, </span><span class="string">'HandleException'</span><span class="keyword">]);<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; }<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; protected function </span><span class="default">HandleError </span><span class="keyword">( </span><span class="default">$Code</span><span class="keyword">, </span><span class="default">$Message</span><span class="keyword">, </span><span class="default">$File </span><span class="keyword">= </span><span class="default">null</span><span class="keyword">, </span><span class="default">$Line </span><span class="keyword">= </span><span class="default">0</span><span class="keyword">, </span><span class="default">$Context </span><span class="keyword">= [] )<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; {<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="comment">// Handle error here.<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="keyword">}<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; private function </span><span class="default">HandleException </span><span class="keyword">( </span><span class="default">$Exception </span><span class="keyword">)<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; {<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="comment">// Handle exception here.<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="keyword">}<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">?&gt;<br />
</span><br />
NOTE: these methods must match the callbacks parameters signatures. I put</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="120196""></a>
  <div class="note">
   <strong class="user">dev at codesatori dot com</strong>
   <a href="#120196" class="date">21-Nov-2016 03:51</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
For those of you wanting to convert PHP errors to ErrorExceptions (useful), but frustrated with the script being halted on every E_NOTICE et al. In your error handler, simply create the ErrorException, and then either throw it (script halted), or pass the object directly (script continues) to your exception handler function.<br />
<br />
<span class="default">&lt;?php<br />
</span><span class="keyword">const </span><span class="default">EXIT_ON_ALL_PHP_ERRORS </span><span class="keyword">= </span><span class="default">false</span><span class="keyword">; </span><span class="comment">// or true<br />
<br />
</span><span class="keyword">function </span><span class="default">proc_error</span><span class="keyword">(</span><span class="default">$errno</span><span class="keyword">, </span><span class="default">$errstr</span><span class="keyword">, </span><span class="default">$errfile</span><span class="keyword">, </span><span class="default">$errline</span><span class="keyword">) <br />
{<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">$e </span><span class="keyword">= new </span><span class="default">ErrorException</span><span class="keyword">(</span><span class="default">$errstr</span><span class="keyword">, </span><span class="default">0</span><span class="keyword">, </span><span class="default">$errno</span><span class="keyword">, </span><span class="default">$errfile</span><span class="keyword">, </span><span class="default">$errline</span><span class="keyword">);<br />
&nbsp;&nbsp;&nbsp; <br />
&nbsp;&nbsp;&nbsp; if (</span><span class="default">EXIT_ON_ALL_PHP_ERRORS</span><span class="keyword">) {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; throw </span><span class="default">$e</span><span class="keyword">; </span><span class="comment">// This will halt your script.<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">} else {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">proc_exception</span><span class="keyword">(</span><span class="default">$e</span><span class="keyword">); </span><span class="comment">// This will let it continue.<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">}<br />
}<br />
<br />
</span><span class="default">set_error_handler</span><span class="keyword">(</span><span class="string">"proc_error"</span><span class="keyword">);<br />
</span><span class="default">set_exception_handler</span><span class="keyword">(</span><span class="string">"proc_exception"</span><span class="keyword">);<br />
</span><span class="default">?&gt;<br />
</span><br />
You could further customize the error severity level (from $errno, match bitmasks with error level constants) at which the script is halted or allowed to continue. The above simply allows passthru for PHP errors' default behavior. <br />
<br />
If your exception handler is receiving both error ErrorExceptions (with severity level etc.) and other types of uncaught Exceptions, then use a <span class="default">&lt;?php </span><span class="keyword">if (</span><span class="default">$e </span><span class="keyword">instanceof </span><span class="default">ErrorException</span><span class="keyword">) { </span><span class="comment">// ... } </span><span class="default">?&gt;</span> condition to deal with the variance. I had to further wrap it into a <span class="default">&lt;?php </span><span class="keyword">try { </span><span class="default">$errno </span><span class="keyword">= </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getSeverity</span><span class="keyword">(); } catch (</span><span class="default">Exception $x</span><span class="keyword">) { </span><span class="default">$errno </span><span class="keyword">= </span><span class="default">0 </span><span class="keyword">} ... </span><span class="default">?&gt;</span>, because some EE-s were mysteriously lacking the severity level property (yet to dig in and find out why).</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="115781""></a>
  <div class="note">
   <strong class="user">Josef Spak</strong>
   <a href="#115781" class="date">22-Sep-2014 10:34</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
On GNU/Linux, When an exception handler is called, PHP will end with exit status code 0 instead of 255.<br />
<br />
You can change the exit status code with an exit() call at the end of your custom error handler.</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="114582""></a>
  <div class="note">
   <strong class="user">Anonymous</strong>
   <a href="#114582" class="date">08-Mar-2014 11:42</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
By default the stack trace is pretty unreadable, so you might want to wrap it in &lt;pre&gt; tags. Here I also wrap it in a &lt;div&gt; and set the class 'alert alert-danger' which are CSS classes in the Bootstrap CSS framework to style them red.<br />
<span class="default">&lt;?php<br />
<br />
</span><span class="keyword">function </span><span class="default">exception_handler</span><span class="keyword">(</span><span class="default">$exception</span><span class="keyword">) {<br />
&nbsp; echo </span><span class="string">'&lt;div class="alert alert-danger"&gt;'</span><span class="keyword">;<br />
&nbsp; echo </span><span class="string">'&lt;b&gt;Fatal error&lt;/b&gt;:&nbsp; Uncaught exception \'' </span><span class="keyword">. </span><span class="default">get_class</span><span class="keyword">(</span><span class="default">$exception</span><span class="keyword">) . </span><span class="string">'\' with message '</span><span class="keyword">;<br />
&nbsp; echo </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">() . </span><span class="string">'&lt;br&gt;'</span><span class="keyword">;<br />
&nbsp; echo </span><span class="string">'Stack trace:&lt;pre&gt;' </span><span class="keyword">. </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getTraceAsString</span><span class="keyword">() . </span><span class="string">'&lt;/pre&gt;'</span><span class="keyword">;<br />
&nbsp; echo </span><span class="string">'thrown in &lt;b&gt;' </span><span class="keyword">. </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getFile</span><span class="keyword">() . </span><span class="string">'&lt;/b&gt; on line &lt;b&gt;' </span><span class="keyword">. </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getLine</span><span class="keyword">() . </span><span class="string">'&lt;/b&gt;&lt;br&gt;'</span><span class="keyword">;<br />
&nbsp; echo </span><span class="string">'&lt;/div&gt;'</span><span class="keyword">;<br />
}<br />
<br />
</span><span class="default">set_exception_handler</span><span class="keyword">(</span><span class="string">'exception_handler'</span><span class="keyword">);</span>
</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="111484""></a>
  <div class="note">
   <strong class="user">Anonymous</strong>
   <a href="#111484" class="date">25-Feb-2013 08:51</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
As of PHP 5.4.11....
<br />

<br />
Instead of:
<br />

<br />
Output: Fatal error: Exception thrown without a stack frame in Unknown on line 0
<br />

<br />
This snippet:
<br />

<br />
<span class="default">&lt;?php
<br />
</span><span class="keyword">function </span><span class="default">error_handler</span><span class="keyword">(</span><span class="default">$code</span><span class="keyword">, </span><span class="default">$message</span><span class="keyword">, </span><span class="default">$file</span><span class="keyword">, </span><span class="default">$line</span><span class="keyword">)
<br />
{
<br />
&nbsp;&nbsp;&nbsp; if (</span><span class="default">0 </span><span class="keyword">== </span><span class="default">error_reporting</span><span class="keyword">())
<br />
&nbsp;&nbsp;&nbsp; {
<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; return;
<br />
&nbsp;&nbsp;&nbsp; }
<br />
&nbsp;&nbsp;&nbsp; throw new </span><span class="default">ErrorException</span><span class="keyword">(</span><span class="default">$message</span><span class="keyword">, </span><span class="default">0</span><span class="keyword">, </span><span class="default">$code</span><span class="keyword">, </span><span class="default">$file</span><span class="keyword">, </span><span class="default">$line</span><span class="keyword">);
<br />
}
<br />
function </span><span class="default">exception_handler</span><span class="keyword">(</span><span class="default">$e</span><span class="keyword">)
<br />
{
<br />
&nbsp;&nbsp;&nbsp; </span><span class="comment">// ... normal exception stuff goes here
<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">print </span><span class="default">$undefined</span><span class="keyword">; </span><span class="comment">// This is the underlying problem
<br />
</span><span class="keyword">}
<br />
</span><span class="default">set_error_handler</span><span class="keyword">(</span><span class="string">"error_handler"</span><span class="keyword">);
<br />
</span><span class="default">set_exception_handler</span><span class="keyword">(</span><span class="string">"exception_handler"</span><span class="keyword">);
<br />
throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"Just invoking the exception handler"</span><span class="keyword">);
<br />
</span><span class="default">?&gt;
<br />
</span>
<br />
Now returns:
<br />

<br />
Fatal error: Uncaught exception 'ErrorException' with message 'Undefined variable: undefined' in C:\Apache2\htdocs\error\test.php:13 Stack trace: #0 C:\Apache2\htdocs\error\test.php(13): error_handler(8, 'Undefined varia...', 'C:\Apache2\htdo...', 13, Array) #1 [internal function]: exception_handler(Object(Exception)) #2 {main} thrown in C:\Apache2\htdocs\error\test.php on line 13
<br />

<br />
So it appears that exceptions thrown within exception handler now bypass exception handler.</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="98201""></a>
  <div class="note">
   <strong class="user">pinkgothic at gmail dot com</strong>
   <a href="#98201" class="date">01-Jun-2010 02:30</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
If you're handling sensitive data and you don't want exceptions logging details such as variable contents when you throw them, you may find yourself frustratedly looking for the bits and pieces that make up a normal stack trace output, so you can retain its legibility but just alter a few things. In that case, this may help you:<br />
<br />
<span class="default">&lt;?php<br />
<br />
</span><span class="keyword">function </span><span class="default">exceptionHandler</span><span class="keyword">(</span><span class="default">$exception</span><span class="keyword">) {<br />
<br />
&nbsp;&nbsp;&nbsp; </span><span class="comment">// these are our templates<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">$traceline </span><span class="keyword">= </span><span class="string">"#%s %s(%s): %s(%s)"</span><span class="keyword">;<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">$msg </span><span class="keyword">= </span><span class="string">"PHP Fatal error:&nbsp; Uncaught exception '%s' with message '%s' in %s:%s\nStack trace:\n%s\n&nbsp; thrown in %s on line %s"</span><span class="keyword">;<br />
<br />
&nbsp;&nbsp;&nbsp; </span><span class="comment">// alter your trace as you please, here<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">$trace </span><span class="keyword">= </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getTrace</span><span class="keyword">();<br />
&nbsp;&nbsp;&nbsp; foreach (</span><span class="default">$trace </span><span class="keyword">as </span><span class="default">$key </span><span class="keyword">=&gt; </span><span class="default">$stackPoint</span><span class="keyword">) {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; </span><span class="comment">// I'm converting arguments to their type<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; // (prevents passwords from ever getting logged as anything other than 'string')<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">$trace</span><span class="keyword">[</span><span class="default">$key</span><span class="keyword">][</span><span class="string">'args'</span><span class="keyword">] = </span><span class="default">array_map</span><span class="keyword">(</span><span class="string">'gettype'</span><span class="keyword">, </span><span class="default">$trace</span><span class="keyword">[</span><span class="default">$key</span><span class="keyword">][</span><span class="string">'args'</span><span class="keyword">]);<br />
&nbsp;&nbsp;&nbsp; }<br />
<br />
&nbsp;&nbsp;&nbsp; </span><span class="comment">// build your tracelines<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">$result </span><span class="keyword">= array();<br />
&nbsp;&nbsp;&nbsp; foreach (</span><span class="default">$trace </span><span class="keyword">as </span><span class="default">$key </span><span class="keyword">=&gt; </span><span class="default">$stackPoint</span><span class="keyword">) {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">$result</span><span class="keyword">[] = </span><span class="default">sprintf</span><span class="keyword">(<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">$traceline</span><span class="keyword">,<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">$key</span><span class="keyword">,<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">$stackPoint</span><span class="keyword">[</span><span class="string">'file'</span><span class="keyword">],<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">$stackPoint</span><span class="keyword">[</span><span class="string">'line'</span><span class="keyword">],<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">$stackPoint</span><span class="keyword">[</span><span class="string">'function'</span><span class="keyword">],<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">implode</span><span class="keyword">(</span><span class="string">', '</span><span class="keyword">, </span><span class="default">$stackPoint</span><span class="keyword">[</span><span class="string">'args'</span><span class="keyword">])<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; );<br />
&nbsp;&nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; </span><span class="comment">// trace always ends with {main}<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">$result</span><span class="keyword">[] = </span><span class="string">'#' </span><span class="keyword">. ++</span><span class="default">$key </span><span class="keyword">. </span><span class="string">' {main}'</span><span class="keyword">;<br />
<br />
&nbsp;&nbsp;&nbsp; </span><span class="comment">// write tracelines into main template<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">$msg </span><span class="keyword">= </span><span class="default">sprintf</span><span class="keyword">(<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">$msg</span><span class="keyword">,<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">get_class</span><span class="keyword">(</span><span class="default">$exception</span><span class="keyword">),<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">(),<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getFile</span><span class="keyword">(),<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getLine</span><span class="keyword">(),<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">implode</span><span class="keyword">(</span><span class="string">"\n"</span><span class="keyword">, </span><span class="default">$result</span><span class="keyword">),<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getFile</span><span class="keyword">(),<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getLine</span><span class="keyword">()<br />
&nbsp;&nbsp;&nbsp; );<br />
<br />
&nbsp;&nbsp;&nbsp; </span><span class="comment">// log or echo as you please<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">error_log</span><span class="keyword">(</span><span class="default">$msg</span><span class="keyword">);<br />
}<br />
<br />
</span><span class="default">?&gt;<br />
</span><br />
If you're not a fan of sprintf() or the duplicate $exception-&gt;getFile() and $exception-&gt;getLine() calls you can of course replace that as you like - consider this a mere compilation of the parts.</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="95170""></a>
  <div class="note">
   <strong class="user">Anonymous</strong>
   <a href="#95170" class="date">16-Dec-2009 06:12</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
Things you should be aware of:<br />
<br />
An exception handler handles exceptions that were not caught before. It is the nature of an exception that it discontinues execution of your program - since it declares an exceptional situation in which the program cannot continue (except you catch it).<br />
<br />
Since it has not been catched your code signals it is not being aware of the situation and cant go on.<br />
<br />
This implies: returning to the script is simply impossible when the exception handler has already been called, since an uncaught exception is not a notice. use your own debug- or notice-log-system for things like that.<br />
<br />
Furthermore: While is is still possible to call functions from your script, since the exception handler has already been called exceptions bubbling from that piece of code won't trigger the exception handler again. php will die without leaving any information apart form "uncaught exception with unknown stack frame". So if you call functions from your script, make sure that you catch any exceptions that possibly occur via try..catch inside the exception handler.<br />
<br />
For those of you who misinterpreted the essential meaning of the exception handler: it's only use is to handle the abortion of your script gracefully, e.g. in a project like facebook or wikipedia: render a nice error page, eventually hiding information which shall not leak into the public (instead you may want to write to your log or mail the sys-admin or stuff like that).<br />
<br />
In other words: Redirecting all php-errors form an error-handler using exceptions - including notices - is a very dumb idea, if you do not intend having your script aborted everytime you didn't set a variable (for example).<br />
<br />
my 2 cents.</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="95054""></a>
  <div class="note">
   <strong class="user">Anonymous</strong>
   <a href="#95054" class="date">10-Dec-2009 06:09</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
When an uncaught exception is handled, execution does NOT return to the script, but rather (unexpectedly, on my end anyway) terminates.<br />
<br />
I am using set_error_handler() and set_exception_handler() in conjunction for a system I am currently developing (on v5.3.0 with Xampp). Lets say two E_USER_NOTICES are triggered, the script will die after the first one is processed.<br />
<br />
<span class="default">&lt;?php<br />
&nbsp;&nbsp;&nbsp; set_exception_handler</span><span class="keyword">( </span><span class="string">'exc_handler' </span><span class="keyword">);<br />
&nbsp;&nbsp;&nbsp; function </span><span class="default">exc_handler</span><span class="keyword">(</span><span class="default">$exception</span><span class="keyword">) {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; echo </span><span class="string">"Uncaught exception: " </span><span class="keyword">, </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">(), </span><span class="string">"\n"</span><span class="keyword">;<br />
&nbsp;&nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; function </span><span class="default">errorone</span><span class="keyword">() {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"Test 1"</span><span class="keyword">);<br />
&nbsp;&nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; function </span><span class="default">errortwo</span><span class="keyword">() {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"Test 2"</span><span class="keyword">);<br />
&nbsp;&nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; function </span><span class="default">test</span><span class="keyword">() {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">errorone</span><span class="keyword">();<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">errortwo</span><span class="keyword">();<br />
&nbsp;&nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">test</span><span class="keyword">();<br />
&nbsp;&nbsp;&nbsp; </span><span class="default">test</span><span class="keyword">();<br />
</span><span class="default">?&gt;<br />
</span><br />
Instead of printing (as I'd expect) "Uncaught exception: Text 1\nUncaught exception: Text 2\nUncaught exception: Text 1\nUncaught exception: Text 2\n"<br />
<br />
It is only printed ONCE. I've tried a number of different things, but I can't figure out how to return execution to the script after the EXCEPTION HANDLER has run.<br />
<br />
If anyone has a solution on how to return execution (hence, allow the script to log uncaught exceptions but continue processing) then PLEASE email me! Thanks!</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="88082""></a>
  <div class="note">
   <strong class="user">joshua dot boyle-petrie at its dot monash dot edu</strong>
   <a href="#88082" class="date">08-Jan-2009 11:44</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
Thanks to mastabog we know that throwing an exception within the exception handler will trigger a fatal error and a debugging nightmare.&nbsp; To avoid throwing an exception within there should be easy.<br />
<br />
However, if you use a custom error handler to convert errors to ErrorExceptions suddenly there are a multitude of new ways to accidentally throw exceptions within the exception handler.<br />
<br />
<span class="default">&lt;?php<br />
</span><span class="keyword">function </span><span class="default">error_handler</span><span class="keyword">(</span><span class="default">$code</span><span class="keyword">, </span><span class="default">$message</span><span class="keyword">, </span><span class="default">$file</span><span class="keyword">, </span><span class="default">$line</span><span class="keyword">)<br />
{<br />
&nbsp;&nbsp;&nbsp; if (</span><span class="default">0 </span><span class="keyword">== </span><span class="default">error_reporting</span><span class="keyword">())<br />
&nbsp;&nbsp;&nbsp; {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; return;<br />
&nbsp;&nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; throw new </span><span class="default">ErrorException</span><span class="keyword">(</span><span class="default">$message</span><span class="keyword">, </span><span class="default">0</span><span class="keyword">, </span><span class="default">$code</span><span class="keyword">, </span><span class="default">$file</span><span class="keyword">, </span><span class="default">$line</span><span class="keyword">);<br />
}<br />
function </span><span class="default">exception_handler</span><span class="keyword">(</span><span class="default">$e</span><span class="keyword">)<br />
{<br />
&nbsp;&nbsp;&nbsp; </span><span class="comment">// ... normal exception stuff goes here<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">print </span><span class="default">$undefined</span><span class="keyword">; </span><span class="comment">// This is the underlying problem<br />
</span><span class="keyword">}<br />
</span><span class="default">set_error_handler</span><span class="keyword">(</span><span class="string">"error_handler"</span><span class="keyword">);<br />
</span><span class="default">set_exception_handler</span><span class="keyword">(</span><span class="string">"exception_handler"</span><span class="keyword">);<br />
throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"Just invoking the exception handler"</span><span class="keyword">);<br />
</span><span class="default">?&gt;<br />
</span>Output: Fatal error: Exception thrown without a stack frame in Unknown on line 0<br />
<br />
The best way I have found to avoid this is to wrap up everything in the exception handler in a try/catch block.<br />
<span class="default">&lt;?php<br />
</span><span class="keyword">function </span><span class="default">exception_handler</span><span class="keyword">(</span><span class="default">$e</span><span class="keyword">)<br />
{<br />
&nbsp;&nbsp;&nbsp; try<br />
&nbsp;&nbsp;&nbsp; {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; </span><span class="comment">// ... normal exception stuff goes here<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; </span><span class="keyword">print </span><span class="default">$undefined</span><span class="keyword">; </span><span class="comment">// This is the underlying problem<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">}<br />
&nbsp;&nbsp;&nbsp; catch (</span><span class="default">Exception $e</span><span class="keyword">)<br />
&nbsp;&nbsp;&nbsp; {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; print </span><span class="default">get_class</span><span class="keyword">(</span><span class="default">$e</span><span class="keyword">).</span><span class="string">" thrown within the exception handler. Message: "</span><span class="keyword">.</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">().</span><span class="string">" on line "</span><span class="keyword">.</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getLine</span><span class="keyword">();<br />
&nbsp;&nbsp;&nbsp; }<br />
}<br />
</span><span class="default">?&gt;<br />
</span>Output: ErrorException thrown within the exception handler. Message: Undefined variable: undefined on line 14<br />
<br />
This speeds up debugging and offers some scalability to any other exceptions accidentally thrown within the exception handler.<br />
<br />
Another solution is to restore the error handler at the beginning of the exception handler.&nbsp; While this is a silver bullet in terms of avoiding the ErrorExceptions, debugging messages then rely on the error_reporting() level and the display_errors directive.&nbsp; Why mention this?&nbsp; It might be preferable for production code since we care more about hiding errors from users than convenient debugging messages.</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="82512""></a>
  <div class="note">
   <strong class="user">marques at displague dot com</strong>
   <a href="#82512" class="date">14-Apr-2008 07:19</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
frank,<br />
<br />
Your exception handler is configured to be the handler for all exceptions, yet if a basic 'Exception' is thrown, your static method will error because 'Exception's do not have 'getException'.&nbsp; Because of this I don't see a real purpose to making the uncaught handler a class that extends Exception.&nbsp; <br />
<br />
I do like the idea of using static methods of a general Exception handling class.&nbsp; <br />
<br />
<span class="default">&lt;?php<br />
</span><span class="keyword">class </span><span class="default">ExceptionHandler </span><span class="keyword">{&nbsp;&nbsp; <br />
&nbsp;&nbsp;&nbsp; public static function </span><span class="default">printException</span><span class="keyword">(</span><span class="default">Exception $e</span><span class="keyword">)<br />
&nbsp;&nbsp;&nbsp; {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; print </span><span class="string">'Uncaught '</span><span class="keyword">.</span><span class="default">get_class</span><span class="keyword">(</span><span class="default">$e</span><span class="keyword">).</span><span class="string">', code: ' </span><span class="keyword">. </span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getCode</span><span class="keyword">() . </span><span class="string">"&lt;br /&gt;Message: " </span><span class="keyword">. </span><span class="default">htmlentities</span><span class="keyword">(</span><span class="default">$e</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">()).</span><span class="string">"\n"</span><span class="keyword">;<br />
&nbsp;&nbsp;&nbsp; }<br />
&nbsp;&nbsp; <br />
&nbsp;&nbsp;&nbsp; public static function </span><span class="default">handleException</span><span class="keyword">(</span><span class="default">Exception $e</span><span class="keyword">)<br />
&nbsp;&nbsp;&nbsp; {<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="default">self</span><span class="keyword">::</span><span class="default">printException</span><span class="keyword">(</span><span class="default">$e</span><span class="keyword">);<br />
&nbsp;&nbsp;&nbsp; }<br />
}<br />
<br />
</span><span class="default">set_exception_handler</span><span class="keyword">(array(</span><span class="string">"ExceptionHandler"</span><span class="keyword">, </span><span class="string">"handleException"</span><span class="keyword">));<br />
<br />
class </span><span class="default">NewException </span><span class="keyword">extends </span><span class="default">Exception </span><span class="keyword">{}<br />
try {<br />
&nbsp; throw new </span><span class="default">NewException</span><span class="keyword">(</span><span class="string">"Catch me once"</span><span class="keyword">, </span><span class="default">1</span><span class="keyword">);<br />
} catch (</span><span class="default">Exception $e</span><span class="keyword">) {<br />
&nbsp; </span><span class="default">ExceptionHandler</span><span class="keyword">::</span><span class="default">handleException</span><span class="keyword">(</span><span class="default">$e</span><span class="keyword">);<br />
}<br />
<br />
throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"Catch me twice"</span><span class="keyword">, </span><span class="default">2</span><span class="keyword">);<br />
</span><span class="default">?&gt;<br />
</span><br />
Gives:<br />
Uncaught NewException, code: 1&lt;br /&gt;Message: Catch me once<br />
Uncaught Exception, code: 2&lt;br /&gt;Message: Catch me twice<br />
<br />
There are much more interesting things that can be done like reformating and optionally displaying or emailing them.&nbsp; But this class acts a nice container for those functions.</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="78985""></a>
  <div class="note">
   <strong class="user">frank at netventures dot com dot au</strong>
   <a href="#78985" class="date">05-Nov-2007 10:10</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
Hey all, i've just started to use the exception suite instead of the normal PHP error suite. For those of you looking for an object orientated way to do this without looking down at Glen and Sean's examples (Lesson 1: ALWAYS read the logs!), here you go:<br />
<br />
<span class="default">&lt;?php<br />
<br />
</span><span class="keyword">class </span><span class="default">NewException </span><span class="keyword">extends </span><span class="default">Exception<br />
</span><span class="keyword">{<br />
&nbsp;&nbsp;&nbsp; public function </span><span class="default">__construct</span><span class="keyword">(</span><span class="default">$message</span><span class="keyword">, </span><span class="default">$code</span><span class="keyword">=</span><span class="default">NULL</span><span class="keyword">)<br />
&nbsp;&nbsp;&nbsp; {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; </span><span class="default">parent</span><span class="keyword">::</span><span class="default">__construct</span><span class="keyword">(</span><span class="default">$message</span><span class="keyword">, </span><span class="default">$code</span><span class="keyword">);<br />
&nbsp;&nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; <br />
&nbsp;&nbsp;&nbsp; public function </span><span class="default">__toString</span><span class="keyword">()<br />
&nbsp;&nbsp;&nbsp; {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; return </span><span class="string">"Code: " </span><span class="keyword">. </span><span class="default">$this</span><span class="keyword">-&gt;</span><span class="default">getCode</span><span class="keyword">() . </span><span class="string">"&lt;br /&gt;Message: " </span><span class="keyword">. </span><span class="default">htmlentities</span><span class="keyword">(</span><span class="default">$this</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">());<br />
&nbsp;&nbsp;&nbsp; }<br />
&nbsp;&nbsp;&nbsp; <br />
&nbsp;&nbsp;&nbsp; public function </span><span class="default">getException</span><span class="keyword">()<br />
&nbsp;&nbsp;&nbsp; {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; print </span><span class="default">$this</span><span class="keyword">; </span><span class="comment">// This will print the return from the above method __toString()<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">}<br />
&nbsp;&nbsp;&nbsp; <br />
&nbsp;&nbsp;&nbsp; public static function </span><span class="default">getStaticException</span><span class="keyword">(</span><span class="default">$exception</span><span class="keyword">)<br />
&nbsp;&nbsp;&nbsp; {<br />
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getException</span><span class="keyword">(); </span><span class="comment">// $exception is an instance of this class<br />
&nbsp;&nbsp;&nbsp; </span><span class="keyword">}<br />
}<br />
<br />
</span><span class="default">set_exception_handler</span><span class="keyword">(array(</span><span class="string">"NewException"</span><span class="keyword">, </span><span class="string">"getStaticException"</span><span class="keyword">));<br />
throw new </span><span class="default">NewException</span><span class="keyword">(</span><span class="string">"Catch me!!!"</span><span class="keyword">, </span><span class="default">69</span><span class="keyword">);<br />
<br />
</span><span class="default">?&gt;<br />
</span><br />
Let me know if i'm missing something obvious as I left my glasses at home and I just came back from the Melbourne cup (If I won then I wouldn't be at work still!).</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="75035""></a>
  <div class="note">
   <strong class="user">reg dot php dot manual at entropy dot ch</strong>
   <a href="#75035" class="date">09-May-2007 06:59</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
In my experience, the static keyword is crucial for error handlers which are methods of a class instead of free-standing functions.<br />
<br />
&nbsp;&nbsp;&nbsp; static function exceptionHandler($exception)<br />
<br />
works but <br />
<br />
&nbsp;&nbsp;&nbsp; function exceptionHandler($exception)<br />
<br />
doesn't and results in a "Fatal error: Exception thrown without a stack frame in Unknown on line 0" message.<br />
<br />
"public" is optional as it is the default anyway (but it is probably clearer to write it explicitly).</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="73607""></a>
  <div class="note">
   <strong class="user">Glen</strong>
   <a href="#73607" class="date">03-Mar-2007 12:34</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
If you want a class instance to handle the exception, this is how you do it :<br />
<br />
<span class="default">&lt;?php<br />
</span><span class="keyword">class </span><span class="default">example </span><span class="keyword">{<br />
&nbsp;&nbsp; public function </span><span class="default">__construct</span><span class="keyword">() {<br />
&nbsp;&nbsp; &nbsp; &nbsp; @</span><span class="default">set_exception_handler</span><span class="keyword">(array(</span><span class="default">$this</span><span class="keyword">, </span><span class="string">'exception_handler'</span><span class="keyword">));<br />
&nbsp;&nbsp; &nbsp; &nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">'DOH!!'</span><span class="keyword">);<br />
&nbsp;&nbsp; }<br />
<br />
&nbsp;&nbsp; public function </span><span class="default">exception_handler</span><span class="keyword">(</span><span class="default">$exception</span><span class="keyword">) {<br />
&nbsp;&nbsp; &nbsp; &nbsp; print </span><span class="string">"Exception Caught: "</span><span class="keyword">. </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">() .</span><span class="string">"\n"</span><span class="keyword">;<br />
&nbsp;&nbsp; }<br />
}<br />
<br />
</span><span class="default">$example </span><span class="keyword">= new </span><span class="default">example</span><span class="keyword">;<br />
<br />
</span><span class="default">?&gt;<br />
</span><br />
See the first post (Sean's) for a static example.&nbsp; As Sean points out, the exception_handler function must be declared public.</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="68712""></a>
  <div class="note">
   <strong class="user">mastabog at hotmail dot com</strong>
   <a href="#68712" class="date">08-Aug-2006 07:44</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
A behaviour not documented or discussed enough, yet pretty common is that is that if an exception is thrown from the global exception handler then a fatal error occurs (Exception thrown without a stack frame). That is, if you define your own global exception handler by calling set_exception_handler() and you throw an exception from inside it then this fatal error occurs. It is only natural though, as the callback defined by set_exception_handler() is only called on uncaught (unhandled) exceptions so if you throw one from there then you get this fatal error as there is no exception handler left (you override the php internal one by calling set_exception_handler()), hence no stack frame for it.<br />
<br />
Example:<br />
<br />
<span class="default">&lt;?php<br />
<br />
</span><span class="keyword">function </span><span class="default">myExceptionHandler </span><span class="keyword">(</span><span class="default">Exception $ex</span><span class="keyword">)<br />
{<br />
&nbsp;&nbsp;&nbsp; throw </span><span class="default">$ex</span><span class="keyword">;<br />
}<br />
<br />
</span><span class="default">set_exception_handler</span><span class="keyword">(</span><span class="string">"myExceptionHandler"</span><span class="keyword">);<br />
<br />
throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">"This should cause a fatal error and this message will be lost"</span><span class="keyword">);<br />
<br />
</span><span class="default">?&gt;<br />
</span><br />
Will cause a Fatal error: Exception thrown without a stack frame<br />
<br />
If you skip/comment the set_exception_handler("...") line then the internal PHP global handler will catch the exception and output the exception message and trace (as string) to the browser, allowing you to at least see the exception message.<br />
<br />
While it is a very good idea to always define your own global exception handler by using the set_exception_handler() function, you should pay attention and never throw an exception from it (or if you do then catch it).<br />
<br />
Finally, every serious coder should use an IDE with debugging capabilities. Tracking down an error like this becomes a trivial matter by using simple debugging "Step into" commands (I for one recommend Zend IDE v5.2 at the moment of this writing). I have seen numerous messages on the internet with people wondering why this message pops up.<br />
<br />
Cheers<br />
<br />
p.s. Other causes for this error which are somehow unrelated to this is when you throw an exception from a destructor (the reasons behind that are similar though, the global handler might no longer exist due to the php engine shutting the page down).</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="64110""></a>
  <div class="note">
   <strong class="user">mc-php-doco at oak dot homeunix dot org</strong>
   <a href="#64110" class="date">07-Apr-2006 09:41</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
This seems not to work when calling the PHP binary with the '-r' flag.<br />
<br />
For example, if I run it like this:<br />
<br />
&nbsp;&nbsp;&nbsp; php -r '<br />
&nbsp;&nbsp; &nbsp;&nbsp; function exception_handler($exception) {<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; echo "Uncaught exception: " , $exception-&gt;getMessage(), "\n";<br />
&nbsp;&nbsp; &nbsp;&nbsp; }<br />
&nbsp;<br />
&nbsp;&nbsp; &nbsp;&nbsp; set_exception_handler("exception_handler");<br />
&nbsp;<br />
&nbsp;&nbsp; &nbsp;&nbsp; throw new Exception("Uncaught Exception");<br />
&nbsp;&nbsp; &nbsp;&nbsp; echo "Not Executed\n";<br />
&nbsp;&nbsp;&nbsp; '<br />
<br />
Or if I place it in a file and run it like this:<br />
<br />
&nbsp;&nbsp;&nbsp; php -r 'include "./tmp.php";'<br />
<br />
I get a stack trace instead of having the function 'exception_handler' called.&nbsp; If run it like this:<br />
<br />
&nbsp;&nbsp;&nbsp; php tmp.php<br />
<br />
It works fine.&nbsp; <br />
<br />
(Why run code from '-r'?&nbsp; Sometimes it's useful to add stuff around the include like calls to microtime for benchmarks, or to include a library and then call a few functions from the library, all in an ad-hoc way without having to create new files.)<br />
<br />
PHP versions 5.1.2 and 5.0.4.</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="62154""></a>
  <div class="note">
   <strong class="user">ch at westend dot com</strong>
   <a href="#62154" class="date">21-Feb-2006 07:06</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
It seems that although the Exception contains a backtrace itself, the stack for the debug_backtrace() function is empty when entering an exception handler. This is very inconvinient. See bug #36477.</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
  <a name="58086""></a>
  <div class="note">
   <strong class="user">sean at seanodonnell dot com</strong>
   <a href="#58086" class="date">23-Oct-2005 04:48</a>
   <div class="text">
    <div class="phpcode">
<code><span class="html">
Using the 'set_exception_handler' function within a class, the defined 'exception_handler' method must be declared as 'public' (preferrable 'public static' if you use the "array('example', 'exception_handler')" syntax). 
<br />

<br />
<span class="default">&lt;?php
<br />
</span><span class="keyword">class </span><span class="default">example </span><span class="keyword">{
<br />
&nbsp;&nbsp;&nbsp; public function </span><span class="default">__construct</span><span class="keyword">() {
<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; @</span><span class="default">set_exception_handler</span><span class="keyword">(array(</span><span class="string">'example'</span><span class="keyword">, </span><span class="string">'exception_handler'</span><span class="keyword">));
<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; throw new </span><span class="default">Exception</span><span class="keyword">(</span><span class="string">'DOH!!'</span><span class="keyword">);
<br />
&nbsp;&nbsp;&nbsp; }
<br />

<br />
&nbsp;&nbsp;&nbsp; public static function </span><span class="default">exception_handler</span><span class="keyword">(</span><span class="default">$exception</span><span class="keyword">) {
<br />
&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; print </span><span class="string">"Exception Caught: "</span><span class="keyword">. </span><span class="default">$exception</span><span class="keyword">-&gt;</span><span class="default">getMessage</span><span class="keyword">() .</span><span class="string">"\n"</span><span class="keyword">;
<br />
&nbsp;&nbsp;&nbsp; }
<br />
}
<br />

<br />
</span><span class="default">$example </span><span class="keyword">= new </span><span class="default">example</span><span class="keyword">;
<br />

<br />
echo </span><span class="string">"Not Executed\n"</span><span class="keyword">;
<br />
</span><span class="default">?&gt;</span> 
<br />

<br />
Declaring the 'exception_handler' function as 'private' causes a FATAL ERROR.
<br />

<br />
[derick: red. updated statement about static a bit]</span>
</code>
    </div>
   </div>
  </div>
 <div class="foot"></div>
</div>
</div>
</div></div></body></html>
